{% set name = "vegasflow" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/vegasflow/archive/v{{ version }}.tar.gz
  sha256: 1140d0243b9ada6ebc5c6f11c617d1c0cbfefa5e24d5f23a48fb1e55f565ae1a

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - tensorflow >=2.0.0
    - joblib
    - numpy

test:
  imports:
    - vegasflow
  requires:
    - pytest
    - python {{ python_min }}
  commands:
    - pytest --pyargs vegasflow

about:
  home: https://github.com/N3PDF/vegasflow
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'VegasFlow: accelerating Monte Carlo simulation across multiple hardware platforms'

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
