{% set name = "vegasflow" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/vegasflow/archive/v{{ version }}.tar.gz
  sha256: a546b5bc323e7cda4931e67568a4ad539bcf26d4efb3f569120484a2b04b63bf

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tensorflow >=2.0.0
    - joblib
    - numpy

test:
  imports:
    - vegasflow
  requires:
    - pytest
  commands:
    - pytest --pyargs vegasflow

about:
  home: https://github.com/N3PDF/vegasflow
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'VegasFlow: accelerating Monte Carlo simulation across multiple hardware platforms'

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
