{% set name = "vegasflow" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/N3PDF/vegasflow/archive/v{{ version }}.tar.gz
  sha256: 8fe88492f87b5cc1f63b391c7dde9db08443706b8ed7240c288bb99f02a85e8d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - tensorflow >=2.0.0
    - joblib
    - numpy

test:
  imports:
    - vegasflow
  requires:
    - pytest
  commands:
    - pytest --pyargs vegasflow

about:
  home: https://github.com/N3PDF/vegasflow
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'VegasFlow: accelerating Monte Carlo simulation across multiple hardware platforms'

extra:
  recipe-maintainers:
    - scarlehoff
    - scarrazza
